# Generated by Django 2.1 on 2020-05-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200519_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodssku',
            options={'verbose_name': '商品SKU', 'verbose_name_plural': '商品SKU'},
        ),
    ]
