# Generated by Django 2.1 on 2020-05-19 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200519_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品所属SPU'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='logo',
            field=models.CharField(max_length=20, verbose_name='标识logo'),
        ),
    ]
