# Generated by Django 2.1 on 2020-05-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200519_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Goods1',
        ),
    ]
