# Generated by Django 2.1 on 2020-05-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20200519_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods1',
            new_name='Goods',
        ),
    ]
