# Generated by Django 2.1 on 2020-05-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20200519_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/goods', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/goods', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/type', verbose_name='商品类型图片'),
        ),
        migrations.AlterField(
            model_name='indexgoodsbanner',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/banner', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='indexpromotionbanner',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/banner', verbose_name='活动图片'),
        ),
    ]
