# Generated by Django 2.1 on 2020-05-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20200520_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='detail',
        ),
    ]
