# Generated by Django 2.1 on 2020-05-28 09:25
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200516_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='comment',
            field=RichTextUploadingField(default='', max_length=256, verbose_name='评论'),
        ),
    ]
