# Generated by Django 2.1 on 2020-05-28 10:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200528_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='comment',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', max_length=256, verbose_name='评论'),
        ),
    ]
